AllCops:
  Include:
    - 'Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Exclude:
    - 'Gemfile'

Metrics/MethodLength:
  Max: 25

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic
  IgnoredMethods:
    - after
    - before

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Style/GuardClause:
  MinBodyLength: 2

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - '*'
    - '='
    - '||='

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
