AllCops:
  Include:
    - 'Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Exclude:
    - 'Gemfile'

Metrics/MethodLength:
  Max: 25

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/Blocks:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
