language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

cache: bundler

bundler_args: --without benchmark development

before_install: gem update --system

after_success: bundle exec codeclimate-test-reporter
