language: ruby

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

cache: bundler

after_success: bundle exec codeclimate-test-reporter

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  code_climate:
    repo_token: 23788f6358c812402884bb474c91ba819e6c096189b8ebe45d3b10b206ed4c67
