language: ruby

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

cache: bundler

bundler_args: --without benchmark development

before_install: gem update --system

after_success: bundle exec codeclimate-test-reporter
