language: ruby

rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - 2.5.0

cache: bundler

bundler_args: --without benchmark development

before_install: gem update --system

after_success: bundle exec codeclimate-test-reporter
